name = "RegexDoc"
reservoir = false
version = "0.1.0"
packagesDir = "../correctness/.lake/packages"

[[require]]
name = "RegexCorrectness"
path = "../correctness"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.26.0"
