name = "RegexCorrectness"
version = "0.1.0"
keywords = ["regex", "verification"]
defaultTargets = ["RegexCorrectness"]

[leanOptions]
# autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0-rc3"

[[require]]
name = "Regex"
path = "../regex"

[[lean_lib]]
name = "RegexCorrectness"
