name = "RegexCorrectness"
version = "0.1.0"
keywords = ["regex", "verification"]
defaultTargets = ["RegexCorrectness"]

[leanOptions]
# autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.16.0-rc2"

[[require]]
name = "Regex"
path = "../"

[[lean_lib]]
name = "RegexCorrectness"
